# Generated by Django 4.2.13 on 2024-06-18 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("email",),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
