# Generated by Django 4.2.13 on 2024-07-28 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, verbose_name="código")),
                ("name", models.CharField(max_length=40, verbose_name="nombre")),
            ],
            options={
                "verbose_name": "departamento",
                "verbose_name_plural": "departamentos",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, verbose_name="código")),
                ("name", models.CharField(max_length=40, verbose_name="nombre")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="core.department",
                        verbose_name="departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "distrito",
                "verbose_name_plural": "distritos",
            },
        ),
        migrations.CreateModel(
            name="Establishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=7, verbose_name="código")),
                (
                    "last_data_capture",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="dirección"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="establishments",
                        to="core.district",
                        verbose_name="distrito",
                    ),
                ),
            ],
            options={
                "verbose_name": "establecimiento",
                "verbose_name_plural": "establecimientos",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.PositiveIntegerField(verbose_name="código")),
                ("name", models.CharField(max_length=40, verbose_name="nombre")),
                (
                    "institution_type",
                    models.CharField(max_length=50, verbose_name="tipo"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="teléfono"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, default="", verbose_name="url"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutions",
                        to="core.establishment",
                        verbose_name="establecimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "institución",
                "verbose_name_plural": "instituciones",
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(upload_to="pictures", verbose_name="imagen"),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen",
                "verbose_name_plural": "imágenes",
            },
        ),
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, verbose_name="código")),
                ("name", models.CharField(max_length=40, verbose_name="nombre")),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localities",
                        to="core.district",
                        verbose_name="distrito",
                    ),
                ),
            ],
            options={
                "verbose_name": "localidad",
                "verbose_name_plural": "localidades",
            },
        ),
        migrations.CreateModel(
            name="InstitutionUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_manager",
                    models.BooleanField(default=False, verbose_name="es administrador"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_users",
                        to="core.institution",
                        verbose_name="institución",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="establishment",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="establishments",
                to="core.locality",
                verbose_name="localidad",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "file",
                    models.FileField(upload_to="documents", verbose_name="documento"),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
            },
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_department"
            ),
        ),
        migrations.AddIndex(
            model_name="picture",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_pictur_content_a2f15c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="locality",
            index=models.Index(fields=["name"], name="core_locali_name_0ff359_idx"),
        ),
        migrations.AddConstraint(
            model_name="locality",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_locality"
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(fields=["name"], name="core_instit_name_dda37a_idx"),
        ),
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_institution"
            ),
        ),
        migrations.AddConstraint(
            model_name="establishment",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_establishment"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_docume_content_343c2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(fields=["name"], name="core_distri_name_3b55fa_idx"),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("code", "department"), name="unique_district"
            ),
        ),
    ]
