# Generated by Django 4.2.13 on 2024-07-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_department_created_at_department_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=256, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="district",
            name="code",
            field=models.CharField(max_length=12, verbose_name="código"),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(max_length=500, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="code",
            field=models.CharField(max_length=12, verbose_name="código"),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="zone_name",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="nombre zona"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=500, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="locality",
            name="code",
            field=models.CharField(max_length=12, verbose_name="código"),
        ),
        migrations.AlterField(
            model_name="locality",
            name="name",
            field=models.CharField(max_length=500, verbose_name="nombre"),
        ),
    ]
