# Generated by Django 4.2.13 on 2024-07-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_department_name_alter_district_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=12, verbose_name="código"),
        ),
    ]
