# Generated by Django 4.2.13 on 2024-07-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_department_code"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="district",
            name="unique_district",
        ),
        migrations.RemoveConstraint(
            model_name="locality",
            name="unique_locality",
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("code", "department"), name="unique_district_in_department"
            ),
        ),
        migrations.AddConstraint(
            model_name="locality",
            constraint=models.UniqueConstraint(
                fields=("code", "district"), name="unique_locality_in_district"
            ),
        ),
    ]
