# Generated by Django 4.2.13 on 2024-07-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_district_unique_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="teléfono"
            ),
        ),
    ]
