# Generated by Django 4.2.13 on 2024-07-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_institution_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="code",
            field=models.BigIntegerField(verbose_name="código"),
        ),
    ]
