# Generated by Django 4.2.15 on 2024-08-31 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_institutionuser_options_institution_users"),
    ]

    operations = []
