# Generated by Django 4.2.15 on 2024-09-01 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_auto_20240831_1944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="users",
            field=models.ManyToManyField(
                related_name="institutions",
                through="core.InstitutionUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuarios",
            ),
        ),
    ]
