# Generated by Django 4.2.15 on 2024-09-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_institution_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descripción"
                    ),
                ),
                (
                    "document",
                    models.FileField(upload_to="resources", verbose_name="documento"),
                ),
            ],
        ),
    ]
