# Generated by Django 4.2.15 on 2024-09-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_resource_options_resource_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="resources", verbose_name="documento"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(blank=True, default="", verbose_name="URL"),
        ),
    ]
