# Generated by Django 4.2.16 on 2024-09-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_resource_options_resource_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="website",
            field=models.URLField(blank=True, default="", verbose_name="sitio web"),
        ),
    ]
