# Generated by Django 4.2.16 on 2024-09-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_institution_website"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="institution",
            name="unique_institution",
        ),
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.UniqueConstraint(
                fields=("code", "establishment"),
                name="unique_establishment_institution",
            ),
        ),
    ]
