# Generated by Django 4.2.16 on 2024-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_institution_unique_institution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishment",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
                verbose_name="latitud",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
                verbose_name="longitud",
            ),
        ),
    ]
