# Generated by Django 4.2.16 on 2024-09-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_establishment_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="code",
            field=models.CharField(max_length=12, verbose_name="código"),
        ),
    ]
