# Generated by Django 4.2.15 on 2024-08-22 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_alter_institutionuser_options_institution_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="año")),
            ],
            options={
                "verbose_name": "período de rendición",
                "verbose_name_plural": "períodos de rendición",
            },
        ),
        migrations.CreateModel(
            name="Disbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateField(verbose_name="fecha de desembolso"),
                ),
                (
                    "amount_disbursed",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="monto desembolsado",
                    ),
                ),
                (
                    "funds_origin",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="origen del ingreso",
                    ),
                ),
                (
                    "origin_details",
                    models.TextField(blank=True, default="", verbose_name="marco"),
                ),
                ("due_date", models.DateField(verbose_name="fecha a rendir")),
                (
                    "principal_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="nombre del director",
                    ),
                ),
                (
                    "principal_issued_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="C.I. del director",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="tipo de pago",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, default="", verbose_name="observaciones"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursements",
                        to="core.institution",
                        verbose_name="institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "desembolso",
                "verbose_name_plural": "desembolsos",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivered_via",
                    models.CharField(max_length=250, verbose_name="recepción"),
                ),
                (
                    "disbursement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="accountability.disbursement",
                        verbose_name="desembolso",
                    ),
                ),
            ],
            options={
                "verbose_name": "rendición",
                "verbose_name_plural": "rendiciones",
            },
        ),
        migrations.CreateModel(
            name="ReportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=20, unique=True, verbose_name="codigo"),
                ),
                ("value", models.CharField(max_length=200, verbose_name="nombre")),
            ],
        ),
        migrations.CreateModel(
            name="Resolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.PositiveSmallIntegerField(verbose_name="nro. resolución"),
                ),
                (
                    "document_year",
                    models.PositiveSmallIntegerField(verbose_name="año de resolución"),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="resolutions", verbose_name="documento de resolución"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_date", models.DateField(verbose_name="fecha")),
                (
                    "voucher_number",
                    models.CharField(
                        max_length=30, verbose_name="número de comprobante"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="accountability.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "comprobante",
                "verbose_name_plural": "comprobantes",
            },
        ),
        migrations.CreateModel(
            name="VoucherType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de comprobante",
                "verbose_name_plural": "tipos de comprobante",
            },
        ),
        migrations.CreateModel(
            name="VoucherDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="concepto"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="precio total"
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="accountability.voucher",
                        verbose_name="comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle de comprobante",
                "verbose_name_plural": "detalles de comprobante",
            },
        ),
        migrations.AddField(
            model_name="voucher",
            name="voucher_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vouchers",
                to="accountability.vouchertype",
                verbose_name="tipo de comprobante",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accountability.reportstatus",
                verbose_name="estado",
            ),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="resolution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disbursements",
                to="accountability.resolution",
                verbose_name="resolución",
            ),
        ),
    ]
