# Generated by Django 4.2.15 on 2024-08-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0002_alter_resolution_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_date", models.DateField(verbose_name="fecha")),
                (
                    "receipt_number",
                    models.CharField(
                        max_length=30, verbose_name="número de comprobante"
                    ),
                ),
                (
                    "object_of_expenditure",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Objeto de gasto",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="concepto"),
                ),
                ("total", models.PositiveIntegerField(null=True, verbose_name="Total")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "comprobante",
                "verbose_name_plural": "comprobantes",
            },
        ),
        migrations.RemoveField(
            model_name="voucherdetail",
            name="voucher",
        ),
        migrations.AlterModelOptions(
            name="resolution",
            options={
                "verbose_name": "resolución",
                "verbose_name_plural": "resoluciones",
            },
        ),
        migrations.RenameModel(
            old_name="VoucherType",
            new_name="ReceiptType",
        ),
        migrations.DeleteModel(
            name="Voucher",
        ),
        migrations.DeleteModel(
            name="VoucherDetail",
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="accountability.receipttype",
                verbose_name="tipo de comprobante",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vouchers",
                to="accountability.report",
            ),
        ),
    ]
