# Generated by Django 4.2.15 on 2024-08-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0003_receipt_remove_voucherdetail_voucher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="accountability.report",
            ),
        ),
    ]
