# Generated by Django 4.2.15 on 2024-08-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0004_alter_receipt_report"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountingYear",
        ),
        migrations.AlterField(
            model_name="disbursement",
            name="amount_disbursed",
            field=models.IntegerField(null=True, verbose_name="monto desembolsado"),
        ),
    ]
