# Generated by Django 4.2.15 on 2024-08-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0005_delete_accountingyear_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=2000, verbose_name="concepto"
            ),
        ),
    ]
