# Generated by Django 4.2.15 on 2024-08-31 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0006_alter_receipt_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.PositiveSmallIntegerField(verbose_name="código")),
                ("value", models.CharField(max_length=250, verbose_name="nombre")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accountability.accountobject",
                        verbose_name="categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "objeto",
                "verbose_name_plural": "objetos",
            },
        ),
        migrations.AlterModelOptions(
            name="reportstatus",
            options={
                "verbose_name": "Estado de rendición",
                "verbose_name_plural": "Estados de rendición",
            },
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="description",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="total",
        ),
        migrations.AlterField(
            model_name="reportstatus",
            name="key",
            field=models.CharField(max_length=20, unique=True, verbose_name="código"),
        ),
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="concepto"),
                ),
                ("unit_price", models.IntegerField(verbose_name="precio unitario")),
                ("quantity", models.FloatField(default=1, verbose_name="cantidad")),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accountability.receipt",
                        verbose_name="comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle",
                "verbose_name_plural": "detalles",
            },
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="object_of_expenditure",
        ),
        migrations.AddField(
            model_name="receipt",
            name="object_of_expenditure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accountability.accountobject",
                verbose_name="objeto de gasto",
                null=True,
            ),
        ),
    ]
