# Generated by Django 4.2.15 on 2024-09-01 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0008_auto_20240831_1944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disbursement",
            name="resolution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disbursements",
                to="accountability.resolution",
                verbose_name="resolución",
            ),
        ),
    ]
