# Generated by Django 4.2.15 on 2024-09-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0009_alter_disbursement_resolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="receipts", verbose_name="documento"
            ),
        ),
    ]
