# Generated by Django 4.2.15 on 2024-09-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0010_receipt_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisbursementOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(verbose_name="código")),
            ],
            options={
                "verbose_name": "origen del ingreso",
                "verbose_name_plural": "orígenes del ingreso",
            },
        ),
        migrations.CreateModel(
            name="OriginDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="nombre")),
            ],
            options={
                "verbose_name": "marco",
                "verbose_name_plural": "marcos",
            },
        ),
        migrations.RemoveField(model_name="disbursement", name="funds_origin"),
        migrations.RemoveField(model_name="disbursement", name="origin_details"),
        migrations.AddField(
            model_name="disbursement",
            name="funds_origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disbursements",
                to="accountability.disbursementorigin",
            ),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="origin_details",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disbursements",
                to="accountability.origindetail",
            ),
        ),
    ]
