# Generated by Django 4.2.15 on 2024-09-04 04:01

from django.db import migrations


def add_funds_origin(apps, schema_editor):
    DisbursementOrigin = apps.get_model("accountability", "DisbursementOrigin")
    for code in (834, 894):
        DisbursementOrigin.objects.create(code=code)


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0011_disbursementorigin_origindetail_and_more"),
    ]

    operations = [
        migrations.RunPython(add_funds_origin, migrations.RunPython.noop),
    ]
