# Generated by Django 4.2.15 on 2024-09-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0013_paymenttype_alter_disbursement_funds_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="accountability.report",
                verbose_name="rendición",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="disbursement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="accountability.disbursement",
                verbose_name="desembolso",
            ),
        ),
    ]
