# Generated by Django 4.2.15 on 2024-09-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0014_alter_receipt_report_alter_report_disbursement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
        ),
        migrations.AlterField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
        ),
    ]
