# Generated by Django 4.2.16 on 2024-09-08 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0015_alter_report_created_at_alter_report_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="object_of_expenditure",
        ),
        migrations.AddField(
            model_name="disbursement",
            name="resolution_amount",
            field=models.PositiveIntegerField(
                null=True, verbose_name="Monto resolución"
            ),
        ),
        migrations.AddField(
            model_name="receiptitem",
            name="object_of_expenditure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accountability.accountobject",
                verbose_name="objeto de gasto",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="balance",
            field=models.IntegerField(null=True, verbose_name="saldo"),
        ),
        migrations.AddField(
            model_name="report",
            name="comments",
            field=models.TextField(
                blank=True, default="", verbose_name="observaciones"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="report_date",
            field=models.DateField(
                editable=False, null=True, verbose_name="fecha de rendición"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reported_amount",
            field=models.PositiveIntegerField(
                editable=False, null=True, verbose_name="monto rendido"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[("cancelado", "Cancelado"), ("pendente", "Pendente")],
                default="pendente",
                editable=False,
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ReportStatus",
        ),
    ]
