# Generated by Django 4.2.16 on 2024-09-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0017_alter_resolution_document_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disbursement",
            name="disbursement_date",
            field=models.DateField(null=True, verbose_name="fecha de desembolso"),
        ),
        migrations.AlterField(
            model_name="disbursement",
            name="due_date",
            field=models.DateField(null=True, verbose_name="fecha a rendir"),
        ),
    ]
