# Generated by Django 4.2.16 on 2024-09-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0018_alter_disbursement_disbursement_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resolution",
            name="document_number",
            field=models.PositiveIntegerField(
                null=True, verbose_name="nro. resolución"
            ),
        ),
        migrations.AlterField(
            model_name="resolution",
            name="document_year",
            field=models.PositiveIntegerField(
                null=True, verbose_name="año de resolución"
            ),
        ),
    ]
