# Generated by Django 4.2.16 on 2024-09-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0019_alter_resolution_document_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="receipt_date",
            field=models.DateField(null=True, verbose_name="fecha"),
        ),
    ]
