# Generated by Django 4.2.16 on 2024-09-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0020_alter_receipt_receipt_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disbursementorigin",
            options={
                "ordering": ["code"],
                "verbose_name": "origen del ingreso",
                "verbose_name_plural": "orígenes del ingreso",
            },
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="object_of_expenditure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_items",
                to="accountability.accountobject",
                verbose_name="objeto de gasto",
            ),
        ),
    ]
