# Generated by Django 4.2.16 on 2024-09-10 10:51

import accountability.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0021_alter_disbursementorigin_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[accountability.models.validate_ruc],
                        verbose_name="ruc",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Razón social")),
            ],
            options={
                "verbose_name": "proveedor",
                "verbose_name_plural": "proveedores",
            },
        ),
        migrations.AddField(
            model_name="receipt",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accountability.provider",
                verbose_name="proveedor",
            ),
        ),
    ]
