# Generated by Django 4.2.16 on 2024-09-11 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_establishment_latitude_and_more"),
        ("accountability", "0022_provider_receipt_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="disbursement",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accountability.disbursement",
                verbose_name="desembolso",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="institution",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.institution",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="institution",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.institution",
            ),
        ),
    ]
