# Generated by Django 4.2.16 on 2024-09-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accountability",
            "0025_remove_report_balance_remove_report_reported_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptitem",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="concepto"
            ),
        ),
    ]
