# Generated by Django 4.2.16 on 2024-10-09 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0027_resolution_full_document_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text='Si deja el campo en blanco, se mostrará "Sin datos"',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accountability.provider",
                verbose_name="proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[("cancelado", "Cancelado"), ("pendente", "Pendente")],
                default="pendente",
                editable=False,
                max_length=20,
                verbose_name="estado",
            ),
        ),
    ]
