# Generated by Django 4.2.16 on 2024-10-10 19:19
from dateutil.relativedelta import relativedelta
from django.db import migrations


def remove_empty_receipt_number(apps, schema_editor):
    Receipt = apps.get_model("accountability", "Receipt")
    Receipt.objects.filter(receipt_number__regex=r"^0+$").update(receipt_number="")


def update_due_dates(apps, schema_editor):
    Disbursement = apps.get_model("accountability", "Disbursement")
    for d in Disbursement.objects.all():
        if d.disbursement_date:
            d.due_date = d.disbursement_date + relativedelta(months=3, days=15)
            d.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0030_alter_receipt_receipt_number"),
    ]

    operations = [
        migrations.RunPython(remove_empty_receipt_number, migrations.RunPython.noop),
        migrations.RunPython(update_due_dates, migrations.RunPython.noop),
    ]
