# Generated by Django 4.2.16 on 2024-10-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0031_auto_20241010_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="disbursement",
            name="is_historical",
            field=models.BooleanField(default=False, verbose_name="histórico"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="receipt_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Si deja el campo en blanco, se mostrará "Sin datos"',
                max_length=30,
                verbose_name="número de comprobante",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[("cancelado", "Cancelado"), ("pendente", "Pendiente")],
                default="pendente",
                editable=False,
                max_length=20,
                verbose_name="estado",
            ),
        ),
    ]
