# Generated by Django 4.2.16 on 2024-10-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0032_disbursement_is_historical_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disbursement",
            name="is_historical",
            field=models.BooleanField(
                default=False,
                help_text="Si activa el histórico, se desactiva el semáforo de fecha de rendición.",
                verbose_name="histórico",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_date",
            field=models.DateField(null=True, verbose_name="fecha de rendición"),
        ),
    ]
