# Generated by Django 4.2.16 on 2024-10-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0033_alter_disbursement_is_historical_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountobject",
            name="comments",
            field=models.TextField(
                blank=True, default="", verbose_name="observaciones"
            ),
        ),
    ]
